### ISSUE TITLE
Move all header files to include folder.

### ISSUE THREAD

**Issue by hitanshu-mehta** [hitanshu-mehta/Intrusion-Detection-using-machine-learning-techniques#1]
- create a include folder in src.
- move all the header files to include folder.
- also change the location of those files in CMakeLists.txt

**Comment by arshbeerSingh** [comment]
Can I work on this issue?

**Comment by hitanshu-mehta** [comment]
@arshbeerSingh Sure. I have assigned to you!

**Comment by arshbeerSingh** [comment]
Thank You very much @hitanshu-mehta  for giving me the opportunity to contribute to this project

**Comment by hitanshu-mehta** [comment]
Welcome 😊. Thank you for contributing.
